### ISSUE TITLE
Show warning for subscriptions to non-existent classes/events

### ISSUE THREAD

**Issue by mishak87** [juzna/intellij-kdyby-events#6]

**Comment by fprochazka** [comment]
How will I check that the event doesn't exists? :) Doctrine and other tools do not publis their events in  properties just like Nette does.

**Comment by matej21** [comment]
@fprochazka: but ClassName::onFoo syntax is used only by nette events, am I right? So we can show warning only if event name looks like nette event

**Comment by mishak87** [comment]
@fprochazka Seriously I feel like you are intentionally trolling me any time you get the chance without thinking.
Assuming you had read documentation of [kdyby/events](https://github.com/Kdyby/Events/blob/v2.0.2/docs/en/index.md) you actually wrote. How can you expect I was talking about Doctrine style events. Of course there is no other relevant case then Nette style events.

To spell it out: Warning should be shown if either `class` or `event` part of subscribed event written using `class::event` syntax is non-existent. Preferably accounting for phpDoc methods and at least assuming of `$this->on<Name>()` magic for Nette\Object descendants.

@matej21  To extend the idea it might be useful to have warning if such method is not public or dynamic. _I am not sure if there are some cases where classes are not possible to use._

**Comment by fprochazka** [comment]
@mishak87 you shouldn't be automatically expecting the worse. To be honest, I haven't really noticed the repository name and by the time I was writing the comment, I thought that you're talking about compile-time check in Events compiler extension ;)

**Comment by mishak87** [comment]
@fprochazka Right that explains the

> How will I check

I thought it was a bit odd :laughing:
