### ISSUE TITLE
Inspections in CompilerExtension classes

### ISSUE THREAD

**Issue by fprochazka** [juzna/intellij-kdyby-events#9]
This probably shouldn't be happening?

![snimek obrazovky porizeny 2014-10-02 23 59 16](https://cloud.githubusercontent.com/assets/158625/4499209/70d93332-4a7f-11e4-8e76-70f12c507cea.png)

**Comment by matej21** [comment]
Thanks for reporting! I will release fixed version ASAP

**Comment by fprochazka** [comment]
That was fast, thank you! :)
